
(()=>{
const root=document.getElementById('pouch-preview'),content=root.querySelector('main');
let view='today',product={brand:'Zyn',mg:6},notice='',entries=[],purchases=[];
const localDate=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
let lastAdded=null;
try{const saved=JSON.parse(localStorage.getItem('pouch-tracker-v1'));if(saved){product=saved.product;entries=saved.entries;purchases=saved.purchases}}catch{}
const persist=()=>{try{localStorage.setItem('pouch-tracker-v1',JSON.stringify({version:1,product,entries,purchases}));return true}catch{alert('Could not save. Please export your data before closing the app.');return false}};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>'$'+n.toFixed(2),time=()=>new Date().toLocaleTimeString([], {hour:'numeric',minute:'2-digit'});
const items=()=>[...entries,...purchases].sort((a,b)=>b.id-a.id);
function rows(list){return list.map(e=>`<div class="entry"><div>${e.type==='pouch'?`${esc(e.brand)} · ${e.mg} mg`:e.type==='craving'?`Craving · ${e.intensity}/5`:`${esc(e.brand)} · ${e.tins} tin${e.tins>1?'s':''}`}<small>${esc(e.time)}${e.replacement?' · '+esc(e.replacement):''}</small></div>${e.type==='purchase'?`<span>${money(e.amount)}</span>`:''}<button class="link" data-delete="${e.id}" aria-label="Delete entry">Delete</button></div>`).join('')||'<div class="empty">No entries yet.</div>'}
function render(){
root.querySelectorAll('nav button').forEach(b=>b.setAttribute('aria-current',b.dataset.view===view?'page':'false'));
const today=localDate(new Date()),week=new Date();week.setHours(0,0,0,0);week.setDate(week.getDate()-((week.getDay()+6)%7));const weekKey=localDate(week),month=today.slice(0,7);let total=entries.filter(e=>e.type==='pouch'&&e.date===today),spent=purchases.filter(p=>p.date>=weekKey&&p.date<=today).reduce((s,p)=>s+p.amount,0),monthSpent=purchases.filter(p=>p.date.startsWith(month)&&p.date<=today).reduce((s,p)=>s+p.amount,0);
if(view==='today')content.innerHTML=`<h2>Add pouch</h2><div class="row"><div>${esc(product.brand)} · ${product.mg} mg</div><button class="primary" data-action="pouch">+ Log pouch</button></div><div class="notice" role="status" ${notice?'':'hidden'}>${notice}${notice?'<button class="link" data-action="undo" style="margin-left:12px">Undo</button>':''}</div><h3>Summary</h3><div class="totals"><div><div class="value">${total.length}</div><div class="caption">Pouches</div></div><div><div class="value">${total.reduce((s,e)=>s+e.mg,0)} <small>mg</small></div><div class="caption">Nicotine</div></div></div><h3>Spending</h3><div class="row"><span class="caption">This week</span><span>${money(spent)}</span></div><div class="row"><span class="caption">This month</span><span>${money(monthSpent)}</span></div><div class="actions" style="margin-top:10px"><button class="link" data-action="purchase">+ Log purchase</button></div><details class="recent"><summary>Recent entries <span class="chevron" aria-hidden="true">⌄</span></summary>${rows(entries.filter(e=>e.date===today).slice(0,3))}</details>`;
if(view==='history')content.innerHTML=`<h2>History</h2>${rows(items())}`;
if(view==='trends'){const dates=Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-6+i);return d});const vals=dates.map(d=>{const found=entries.filter(e=>e.date===localDate(d));return found.length?found.length:null}),days=dates.map((d,i)=>i===6?'Today':d.toLocaleDateString([], {weekday:'short'}));content.innerHTML=`<h2>Trends</h2><div class="caption">Pouches per day · this preview</div><div class="bars" role="img" aria-label="Daily pouch counts: ${vals.map((v,i)=>days[i]+': '+(v===null?'unlogged':v)).join(', ')}">${vals.map((n,i)=>`<div class="column"><span>${n===null?'—':n}</span><div class="bar" style="height:${n===null?0:Math.min(n*8,100)}px"></div><small>${days[i]}</small></div>`).join('')}</div><div class="entry"><span>Seven-day average</span><span>${vals.filter(v=>v!==null).length===7?(vals.reduce((a,b)=>a+b,0)/7).toFixed(1)+' pouches':'Not enough data'}</span></div><div class="entry"><span>Purchases this month</span><span>${money(monthSpent)}</span></div><div class="caption">— Unlogged day</div>`}
if(view==='settings')content.innerHTML=`<h2>Settings</h2><h3>Default product</h3><div class="row"><span>${esc(product.brand)} · ${product.mg} mg</span><button class="link" data-action="product">Change</button></div><h3>Your data</h3><div class="caption">Logs are saved on this device. Export a backup before clearing browser data or switching phones.</div><div class="form-actions"><button data-action="export">Export backup</button><button data-action="restore">Restore backup</button></div><input type="file" id="backup-file" accept="application/json,.json" hidden><h3>About totals</h3><div class="caption">Nicotine means labeled pouch content, not nicotine absorbed. Weeks start Monday. Unlogged days are unknown.</div>`;
}
function form(kind){notice='';let fields='';
if(kind==='product')fields=`<label for="pp-brand">Brand</label><select id="pp-brand" name="brand">${['On!','Velo','Zyn'].map(b=>`<option ${b===product.brand?'selected':''}>${b}</option>`).join('')}</select><label for="pp-mg">Labeled mg per pouch</label><select id="pp-mg" name="mg">${[3,6,9,11,12,15].map(n=>`<option value="${n}" ${n===product.mg?'selected':''}>${n} mg</option>`).join('')}</select>`;
if(kind==='craving')fields=`<label for="pp-intensity">Intensity · 1 mild, 5 strongest</label><select id="pp-intensity" name="intensity">${[1,2,3,4,5].map(n=>`<option ${n===3?'selected':''}>${n}</option>`).join('')}</select><label for="pp-replacement">Replacement or delay · optional</label><input id="pp-replacement" name="replacement" placeholder="e.g. gum, walk, wait 10 minutes" maxlength="120">`;
if(kind==='purchase')fields=`<label for="pp-pbrand">Brand</label><select id="pp-pbrand" name="brand"><option>On!</option><option>Velo</option><option selected>Zyn</option></select><label for="pp-tins">Number of tins</label><input id="pp-tins" name="tins" type="number" min="1" step="1" required value="1"><label for="pp-amount">Total paid ($)</label><input id="pp-amount" name="amount" type="number" min="0" step="0.01" required placeholder="8.00"><label for="pp-date">Purchase date</label><input id="pp-date" name="date" type="date" required value="${localDate(new Date())}">`;
content.innerHTML=`<h2>${kind==='product'?'Change product':kind==='craving'?'Log craving':'Log purchase'}</h2><form data-kind="${kind}">${fields}<div class="form-actions"><button class="primary" type="submit">Save</button><button type="button" data-action="cancel">Cancel</button></div></form>`;
}
root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.view){view=b.dataset.view;notice='';render();return}if(b.dataset.delete){const id=Number(b.dataset.delete);entries=entries.filter(x=>x.id!==id);purchases=purchases.filter(x=>x.id!==id);persist();notice='';render();return}const a=b.dataset.action;if(a==='pouch'){lastAdded=Date.now();entries.unshift({id:lastAdded,type:'pouch',...product,date:localDate(new Date()),time:time()});persist();notice='Pouch logged';render()}else if(a==='undo'){entries=entries.filter(e=>e.id!==lastAdded);persist();notice='';render()}else if(a==='export'){const blob=new Blob([JSON.stringify({version:1,product,entries,purchases},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='pouch-tracker-backup.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}else if(a==='restore'){root.querySelector('#backup-file').click()}else if(a==='cancel')render();else if(a)form(a)});
root.addEventListener('submit',e=>{e.preventDefault();const f=e.target,d=new FormData(f),kind=f.dataset.kind;if(kind==='product')product={brand:d.get('brand'),mg:Number(d.get('mg'))};else if(kind==='craving')entries.unshift({id:Date.now(),type:kind,intensity:Number(d.get('intensity')),replacement:d.get('replacement'),time:time()});else purchases.unshift({id:Date.now(),type:kind,brand:d.get('brand'),tins:Number(d.get('tins')),amount:Number(d.get('amount')),date:d.get('date'),time:d.get('date')});persist();render()});
root.addEventListener('change',async e=>{if(e.target.id!=='backup-file'||!e.target.files[0])return;try{const d=JSON.parse(await e.target.files[0].text());const strengths=[3,6,9,11,12,15],brands=['On!','Velo','Zyn'];if(d.version!==1||!brands.includes(d.product?.brand)||!strengths.includes(d.product?.mg)||!Array.isArray(d.entries)||!Array.isArray(d.purchases))throw Error();if(!d.entries.every(x=>x.type==='pouch'&&brands.includes(x.brand)&&strengths.includes(x.mg)&&Number.isFinite(x.id)&&/^\d{4}-\d{2}-\d{2}$/.test(x.date)&&typeof x.time==='string')||!d.purchases.every(x=>x.type==='purchase'&&brands.includes(x.brand)&&Number.isFinite(x.id)&&Number.isInteger(x.tins)&&x.tins>0&&Number.isFinite(x.amount)&&x.amount>=0&&/^\d{4}-\d{2}-\d{2}$/.test(x.date)&&typeof x.time==='string'))throw Error();if(!confirm('Replace device logs with this backup?'))return;product=d.product;entries=d.entries;purchases=d.purchases;persist();render();alert('Backup restored.')}catch{alert('This is not a valid Pouch Tracker backup.')}});
render();
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js');
})();
